//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgrifoodManagement.Web.Views.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _AboutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _AboutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgrifoodManagement.Web.Views.Presentation.Resources._AboutResources", typeof(_AboutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform connects farmers and businesses to create a more efficient and sustainable food supply chain. Whether you&apos;re selling surplus produce or looking for fresh ingredients, we make transactions seamless and data-driven..
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        internal static string MoreButton {
            get {
                return ResourceManager.GetString("MoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We empower farmers by providing insights on market demand, helping them optimize harvests and reduce food waste..
        /// </summary>
        internal static string Quality1Description {
            get {
                return ResourceManager.GetString("Quality1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for Farmers.
        /// </summary>
        internal static string Quality1Title {
            get {
                return ResourceManager.GetString("Quality1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Businesses can find the nearest suppliers with fresh stock, reducing transportation costs and ensuring faster delivery..
        /// </summary>
        internal static string Quality2Description {
            get {
                return ResourceManager.GetString("Quality2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Location-Based Trading.
        /// </summary>
        internal static string Quality2Title {
            get {
                return ResourceManager.GetString("Quality2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced analytics predict demand trends and optimize pricing, ensuring fair trade for sellers and buyers alike..
        /// </summary>
        internal static string Quality3Description {
            get {
                return ResourceManager.GetString("Quality3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered Insights.
        /// </summary>
        internal static string Quality3Title {
            get {
                return ResourceManager.GetString("Quality3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
