//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgrifoodManagement.Web.Views.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _FaqResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _FaqResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgrifoodManagement.Web.Views.Presentation.Resources._FaqResources", typeof(_FaqResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To list your stock, navigate to your announcements page and select &quot;Add New Product.&quot; Provide details such as quantity, category, expiration date, price, and location. You can also upload images and update or archive the listing at any time..
        /// </summary>
        internal static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just head over to our Map page—you’ll see pins for every supplier plotted on an interactive map. Enable location access (or enter an address) to center the view around you, then click any pin to view that supplier’s details..
        /// </summary>
        internal static string Answer2 {
            get {
                return ResourceManager.GetString("Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Forecast page, select your product, set a date range and granularity, then click Run Forecast. You’ll see historical demand (dashed line), predicted demand (solid markers), and a 95% confidence band. A brief summary below—e.g. “Demand is increasing by about 27.9%”—helps you plan inventory and promotions..
        /// </summary>
        internal static string Answer3 {
            get {
                return ResourceManager.GetString("Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use machine learning to analyze historical sales data, current demand, and market trends to estimate future prices. This helps farmers decide whether it&apos;s worth harvesting certain products next season..
        /// </summary>
        internal static string Answer4 {
            get {
                return ResourceManager.GetString("Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium listings appear at the top of search results, increasing visibility. You can purchase premium placements to get more exposure for your products..
        /// </summary>
        internal static string Answer5 {
            get {
                return ResourceManager.GetString("Answer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actually, you can save your favorite products with our Wishlist feature! Just click the heart icon on any product to add it to your Wishlist. Then visit your Account &gt; Wishlist page to see all your saved items in one place. From there, you can quickly move them into your cart or track price changes..
        /// </summary>
        internal static string Answer6 {
            get {
                return ResourceManager.GetString("Answer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find answers to common questions about how our agro-food management platform works..
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I list my stock as a seller?.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I find the nearest supplier?.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I forecast future demand for my products?.
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are price estimations calculated?.
        /// </summary>
        internal static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the premium listing option?.
        /// </summary>
        internal static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does the wishlist work?.
        /// </summary>
        internal static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
