//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgrifoodManagement.Web.Views.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _FeaturesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _FeaturesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgrifoodManagement.Web.Views.Presentation.Resources._FeaturesResources", typeof(_FeaturesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily list, update, or remove product listings, including stock quantity, expiration date, and pricing..
        /// </summary>
        internal static string Feature1Description {
            get {
                return ResourceManager.GetString("Feature1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Stock Management.
        /// </summary>
        internal static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get notified when stock is nearing expiration and move items to a priority sale section to reduce waste..
        /// </summary>
        internal static string Feature2Description {
            get {
                return ResourceManager.GetString("Feature2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Expiry Alerts.
        /// </summary>
        internal static string Feature2Title {
            get {
                return ResourceManager.GetString("Feature2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find products based on location, expiration date, category, price, and demand trends..
        /// </summary>
        internal static string Feature3Description {
            get {
                return ResourceManager.GetString("Feature3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search &amp; Filtering.
        /// </summary>
        internal static string Feature3Title {
            get {
                return ResourceManager.GetString("Feature3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the nearest available stock, reducing transportation costs and ensuring fresher produce..
        /// </summary>
        internal static string Feature4Description {
            get {
                return ResourceManager.GetString("Feature4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps Integration.
        /// </summary>
        internal static string Feature4Title {
            get {
                return ResourceManager.GetString("Feature4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict future demand and price trends based on historical sales data and market conditions..
        /// </summary>
        internal static string Feature5Description {
            get {
                return ResourceManager.GetString("Feature5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered Demand Forecasting.
        /// </summary>
        internal static string Feature5Title {
            get {
                return ResourceManager.GetString("Feature5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically adjust prices based on stock levels, expiration dates, and estimated demand..
        /// </summary>
        internal static string Feature6Description {
            get {
                return ResourceManager.GetString("Feature6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Pricing Optimization.
        /// </summary>
        internal static string Feature6Title {
            get {
                return ResourceManager.GetString("Feature6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform simplifies agro-food resource management by connecting farmers with businesses and optimizing the supply chain..
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
