//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgrifoodManagement.Web.Views.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _MissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgrifoodManagement.Web.Views.Presentation.Resources._MissionResources", typeof(_MissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are dedicated to delivering innovative solutions that enhance decision-making, improve efficiency, and contribute to a smarter, more sustainable future..
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We leverage advanced technologies to create intuitive and reliable solutions that simplify complex processes and improve user experience..
        /// </summary>
        internal static string Mission1Description {
            get {
                return ResourceManager.GetString("Mission1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovation in Technology.
        /// </summary>
        internal static string Mission1Title {
            get {
                return ResourceManager.GetString("Mission1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goal is to provide real-time, data-driven insights that help individuals and businesses make informed and strategic decisions with confidence..
        /// </summary>
        internal static string Mission2Description {
            get {
                return ResourceManager.GetString("Mission2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empowering Decision-Making.
        /// </summary>
        internal static string Mission2Title {
            get {
                return ResourceManager.GetString("Mission2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are committed to optimizing resources and reducing environmental impact through smart, sustainable solutions that drive positive change..
        /// </summary>
        internal static string Mission3Description {
            get {
                return ResourceManager.GetString("Mission3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustainability &amp; Efficiency.
        /// </summary>
        internal static string Mission3Title {
            get {
                return ResourceManager.GetString("Mission3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
