//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgrifoodManagement.Web.Views.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _TestimonialResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _TestimonialResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgrifoodManagement.Web.Views.Presentation.Resources._TestimonialResources", typeof(_TestimonialResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hear from our users and industry experts on how AgriManage is transforming the agri-food market..
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        internal static string Person1JobTitle {
            get {
                return ResourceManager.GetString("Person1JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Popescu.
        /// </summary>
        internal static string Person1Name {
            get {
                return ResourceManager.GetString("Person1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Distributor.
        /// </summary>
        internal static string Person2JobTitle {
            get {
                return ResourceManager.GetString("Person2JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maria Ionescu.
        /// </summary>
        internal static string Person2Name {
            get {
                return ResourceManager.GetString("Person2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Expert.
        /// </summary>
        internal static string Person3JobTitle {
            get {
                return ResourceManager.GetString("Person3JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. Andrei Georgescu.
        /// </summary>
        internal static string Person3Name {
            get {
                return ResourceManager.GetString("Person3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;AgriManage has revolutionized the way I handle my produce. I can easily list my stock with expiration dates and get demand forecasts, which helps me plan for the future.&quot;.
        /// </summary>
        internal static string Testimonial1 {
            get {
                return ResourceManager.GetString("Testimonial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The integration with Google Maps and advanced search features make it easy to find suppliers nearby. Plus, the online payment and wishlist functionalities streamline our procurement process.&quot;.
        /// </summary>
        internal static string Testimonial2 {
            get {
                return ResourceManager.GetString("Testimonial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;AgriManage’s smart analytics, including price adjustment algorithms and demand forecasts, offer unparalleled market insights. It&apos;s a powerful tool for both sellers and buyers in the agri-food sector.&quot;.
        /// </summary>
        internal static string Testimonial3 {
            get {
                return ResourceManager.GetString("Testimonial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
